# Generated by Django 3.2.7 on 2021-09-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemparementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingGenius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=1)),
                ('genius', models.CharField(max_length=15)),
                ('definition', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
