# Generated by Django 3.2.7 on 2021-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('ACCOUNTING', 'ACCOUNTING'), ('DEVELOPMENT', 'DEVELOPMENT'), ('EXECUTIVE', 'EXECUTIVE'), ('GOVERNMENT RELATIONS', 'GOVERNMENT RELATIONS'), ('HUMAN RESOURCES', 'HUMAN RESOURCES'), ('INVENTORY', 'INVENTORY'), ('IT', 'IT'), ('LEGAL', 'LEGAL'), ('MANAGEMENT', 'MANAGEMENT'), ('MARKETING', 'MARKETING'), ('SALES', 'SALES'), ('SERVICE', 'SERVICE'), ('SUPPORT', 'SUPPORT')], default='IT', max_length=50)),
                ('role', models.CharField(choices=[('Front End Dev', 'Front End Dev'), ('Back End Dev', 'Back End Dev'), ('Full Stack Dev', 'Full Stack Dev'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('COO', 'COO'), ('CTO', 'CTO'), ('Assisstant', 'Assisstant'), ('Community Relations', 'Community Relations'), ('Regulatory Admin', 'Regulatory Admin'), ('Personnel and Benefits', 'Personnel and Benefits'), ('Pay roll and AR/ AP', 'Pay roll and AR/ AP'), ('Procurment and Logisitics Admin', 'Procurment and Logisitics Admin'), ('Logisitics Assisstant', 'Logisitics Assisstant'), ('Software Admin', 'Software Admin'), ('Hardware Admin', 'Hardware Admin'), ('Policy and Procedures', 'Policy and Procedures'), ('Health and Safety', 'Health and Safety'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Marketing', 'Marketing'), ('Service', 'Service'), ('Support', 'Support'), ('Inventory', 'Inventory'), ('Accounting', 'Accounting'), ('Legal', 'Legal'), ('Development', 'Development'), ('IT', 'IT'), ('Designer', 'Designer'), ('Content Writer', 'Content Writer'), ('Social Media', 'Social Media'), ('Sr Sales Rep', 'Sr Sales Rep'), ('Sales Rep', 'Sales Rep'), ('Sr. Service Rep', 'Sr. Service Rep'), ('Service Rep', 'Service Rep'), ('Sr. Support Rep', 'Sr. Support Rep'), ('Support Rep', 'Support Rep')], default='IT', max_length=50)),
                ('hourly_rate', models.FloatField()),
            ],
        ),
    ]
